version: '3.8'
services:
  mongo-db-config-1-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-config-data1:/opt/mongo-db/data
      - mongo-db-config-log1:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongod.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --configsvr --replSet cfgrs --port ${DLK_MONGO_DB_CONFIG_1_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_CONFIG_1_IP}
  mongo-db-config-2-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-config-data2:/opt/mongo-db/data
      - mongo-db-config-log2:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --configsvr --replSet cfgrs --port ${DLK_MONGO_DB_CONFIG_2_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_CONFIG_2_IP}
  mongo-db-config-3-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-config-data3:/opt/mongo-db/data
      - mongo-db-config-log3:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --configsvr --replSet cfgrs --port ${DLK_MONGO_DB_CONFIG_3_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_CONFIG_3_IP}
  mongo-db-shard-1-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-shard-data1:/opt/mongo-db/data
      - mongo-db-shard-log1:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --shardsvr --replSet shars --port ${DLK_MONGO_DB_SHARD_1_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_SHARD_1_IP}
  mongo-db-shard-2-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-shard-data2:/opt/mongo-db/data
      - mongo-db-shard-log2:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --shardsvr --replSet shars --port ${DLK_MONGO_DB_SHARD_2_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_SHARD_2_IP}
  mongo-db-shard-3-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-shard-data3:/opt/mongo-db/data
      - mongo-db-shard-log3:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongod --shardsvr --replSet shars --port ${DLK_MONGO_DB_SHARD_3_PORT} --dbpath /opt/mongo-db/data --fork --logpath /opt/mongo-db/log/mongod.log --bind_ip 0.0.0.0
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_SHARD_3_IP}
  mongo-db-router-1-Node:
    image: sloopstash/mongo-db:v7.0.2
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - mongo-db-router-data1:/opt/mongo-db/data
      - mongo-db-router-log1:/opt/mongo-db/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../mongo-db/${DLK_MONGO_DB_VERSION}/conf/supervisor_compose.ini:/etc/supervisord.d/mongo-db.ini
    environment:
      - MONGO_DB_RUN_COMMAND=mongos --configdb cfgrs/${DLK_MONGO_DB_CONFIG_1_IP}:${DLK_MONGO_DB_CONFIG_1_PORT},${DLK_MONGO_DB_CONFIG_2_IP}:${DLK_MONGO_DB_CONFIG_2_PORT},${DLK_MONGO_DB_CONFIG_3_IP}:${DLK_MONGO_DB_CONFIG_3_PORT} --port ${DLK_MONGO_DB_ROUTER_1_PORT} --bind_ip 0.0.0.0  --fork --logpath /opt/mongo-db/log/mongod.log
    networks:
      common:
        ipv4_address: ${DLK_MONGO_DB_ROUTER_1_IP}
volumes:
  mongo-db-config-data1:
    driver: local
  mongo-db-config-data2:
    driver: local
  mongo-db-config-data3:
    driver: local
  mongo-db-shard-data1:
    driver: local
  mongo-db-shard-data2:
    driver: local
  mongo-db-shard-data3:
    driver: local
  mongo-db-router-data1:
    driver: local  
  mongo-db-config-log1:
    driver: local
  mongo-db-config-log2:
    driver: local
  mongo-db-config-log3:
    driver: local
  mongo-db-shard-log1:
    driver: local
  mongo-db-shard-log2:
    driver: local
  mongo-db-shard-log3:
    driver: local
  mongo-db-router-log1:
    driver: local  
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DLK_MONGO_DB_NETWORK}
